name: Accessibility Tests
on: pull_request

jobs:
  accessibility:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Accessibility Tests
        env:
          AXE_API_KEY: ${{ secrets.AXE_API_KEY }}
        run: npx playwright test --grep "@accessibility"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-accessibility-report
          path: playwright-report/
          retention-days: 7
