name: Package Size Report

on: pull_request

permissions:
  pull-requests: write
  contents: read

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Williams-RE/WRE-Server
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Repository Access
        run: |
          git remote -v
          git status

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package size report
        uses: pkg-size/action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
