name: "Package Size Report"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in build/static/js directory
        run: ls build/static/js/

      # Analyze the bundle size and create a badge
      - name: Analyze and Create Badge
        uses: timeowilliams/package-size-badge-action@v1.0.6

        with:
          path: "build/static/js/*.js" # User specifies the path to their JS bundle
          limit: "500 KB" # Bundle size limit
          label: "Bundle Size"
          color: "green"
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
